# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vduXPKUUBSKaSlaq9nlrAXkqBdn7FRx
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib.pyplot as plt

# ---------------------------------------------------------------
# Page config
# ---------------------------------------------------------------
st.set_page_config(page_title="Gbolahan Oladosu – Portfolio", layout="wide")


# ---------------------------------------------------------------
# Load model (if available)
# ---------------------------------------------------------------
@st.cache_resource
def load_model():
    try:
        pipeline = joblib.load("xgb_dropout_pipeline.pkl")
        return pipeline
    except:
        return None

pipeline = load_model()


# ---------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to:", ["Home", "Resume", "Projects", "Dropout Predictor"])


# ---------------------------------------------------------------
# HOME PAGE
# ---------------------------------------------------------------
if page == "Home":
    st.title("Welcome – Gbolahan Oladosu")
    st.image("assets/headshot.jpg", width=220)
    st.subheader("Clinical Laboratory Scientist → Aspiring Clinical Data Scientist")

    st.markdown("""
    I am **Gbolahan Abdul-Rahman Oladosu**, currently working as a Clinical
    Laboratory Scientist and pursuing my M.S. in Data Science at Eastern University.

    My interests include:

    - Clinical trial analytics
    - Dropout prediction and patient retention
    - Healthcare & EHR machine learning
    - Model interpretability and fairness
    """)


# ---------------------------------------------------------------
# RESUME PAGE
# ---------------------------------------------------------------
elif page == "Resume":
    st.title("Resume")

    st.header("Education")
    st.write("""
    - M.S. Data Science – Eastern University
    - M.S. Biomedical Science – Roosevelt University
    """)

    st.header("Work Experience")
    st.write("""
    **Clinical Laboratory Scientist – Insight Hospital, Chicago**
    - High-complexity diagnostic testing
    - Quality control & lab operations
    - Applying data-driven thinking
    """)

    st.header("Skills")
    st.write("""
    - Python, R, SQL
    - scikit-learn, XGBoost, SHAP
    - Machine learning interpretability
    - Clinical and healthcare analytics
    """)

    st.image("assets/project_image.png", caption="Clinical Trial Analytics")


# ---------------------------------------------------------------
# PROJECTS PAGE
# ---------------------------------------------------------------
elif page == "Projects":
    st.title("Projects")

    st.subheader("Clinical Trial Dropout Prediction (Capstone Project)")
    st.write("""
    - Predicts whether a participant will drop out based on early-visit data
    - Models: Logistic Regression, Random Forest, XGBoost
    - Interpretability using SHAP
    """)

    st.info("""
    **Note:** All MSDS classwork remains private for academic integrity.
    """)


# ---------------------------------------------------------------
# DROPOUT PREDICTOR PAGE
# ---------------------------------------------------------------
elif page == "Dropout Predictor":
    st.title("Clinical Trial Dropout Predictor")

    if pipeline is None:
        st.error("No model file found. Upload xgb_dropout_pipeline.pkl to your project folder.")
    else:
        st.markdown("Enter participant information below:")

        age = st.number_input("Age", min_value=18, max_value=100, value=65)
        sex = st.selectbox("Sex", ["Male", "Female"])
        race = st.selectbox("Race", ["White", "Black", "Asian", "Hispanic", "Other"])

        BMI = st.slider("BMI", 15.0, 45.0, 27.0)
        baseline_lab_score = st.slider("Baseline Lab Score", 0.0, 100.0, 50.0)
        disease_severity = st.slider("Disease Severity", 0.0, 10.0, 5.0)

        prior_treatments = st.number_input("Prior Treatments", 0, 20, 1)
        visit1_symptom_score = st.slider("Visit 1 Symptom Score", 0.0, 100.0, 50.0)
        visit1_adherence_rate = st.slider("Visit 1 Adherence", 0.0, 100.0, 80.0)
        visit1_AE_count = st.number_input("Visit 1 AE Count", 0, 20, 0)

        visit2_symptom_score = st.slider("Visit 2 Symptom Score", 0.0, 100.0, 45.0)
        visit2_adherence_rate = st.slider("Visit 2 Adherence", 0.0, 100.0, 75.0)
        visit2_AE_count = st.number_input("Visit 2 AE Count", 0, 20, 0)

        missed_appointments = st.number_input("Missed Appointments", 0, 20, 0)
        communication_score = st.slider("Communication Score", 0.0, 100.0, 60.0)

        if st.button("Predict Dropout Risk"):
            input_df = pd.DataFrame([{
                "age": age,
                "sex": sex,
                "race": race,
                "BMI": BMI,
                "baseline_lab_score": baseline_lab_score,
                "disease_severity": disease_severity,
                "prior_treatments": prior_treatments,
                "visit1_symptom_score": visit1_symptom_score,
                "visit1_adherence_rate": visit1_adherence_rate,
                "visit1_AE_count": visit1_AE_count,
                "visit2_symptom_score": visit2_symptom_score,
                "visit2_adherence_rate": visit2_adherence_rate,
                "visit2_AE_count": visit2_AE_count,
                "missed_appointments": missed_appointments,
                "communication_score": communication_score
            }])

            clinical_logic = pipeline.named_steps["clinical_logic"]
            missing_flags = pipeline.named_steps["missing_flags"]
            preprocess = pipeline.named_steps["preprocess"]
            model = pipeline.named_steps["model"]

            X_logic = clinical_logic.transform(input_df)
            X_flags = missing_flags.transform(X_logic)
            X_prep = preprocess.transform(X_flags)

            prob = model.predict_proba(X_prep)[0, 1]
            pred = model.predict(X_prep)[0]

            st.subheader("Prediction")
            st.write(f"**Dropout Probability:** `{prob:.3f}`")
            st.write(f"**Predicted Class:** {'Dropout' if pred == 1 else 'Completer'}")

            # SHAP
            explainer = shap.TreeExplainer(model)
            shap_values = explainer.shap_values(X_prep)

            st.subheader("Feature Importance (SHAP)")
            shap.initjs()
            fig, ax = plt.subplots(figsize=(8,4))
            shap.bar_plot(shap_values[0], max_display=10, show=False)
            st.pyplot(fig)