# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vduXPKUUBSKaSlaq9nlrAXkqBdn7FRx
"""
import os
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib.pyplot as plt

from sklearn.base import BaseEstimator, TransformerMixin  # needed for the custom transformer

# ============================
# 1. Custom Transformers
# ============================

class ClinicalConsistencyTransformer(BaseEstimator, TransformerMixin):
    """
    1. Age cleaning:
       - Any age < min_age is set to min_age (assume all participants are adults).

    2. Visit logic:
       - If ALL Visit 1 variables are missing, clear ALL Visit 2 variables to NaN.
       - This only triggers when visit1_symptom_score, visit1_adherence_rate, and visit1_AE_count
         are ALL NaN. If symptom is present (your 150-row case), nothing is touched.
    """
    def __init__(self,
                 visit1_cols=None,
                 visit2_cols=None,
                 age_col='age',
                 min_age=18):
        self.visit1_cols = visit1_cols or [
            'visit1_symptom_score',
            'visit1_adherence_rate',
            'visit1_AE_count'
        ]
        self.visit2_cols = visit2_cols or [
            'visit2_symptom_score',
            'visit2_adherence_rate',
            'visit2_AE_count'
        ]
        self.age_col = age_col
        self.min_age = min_age

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        X = X.copy()

        # --- Age cleaning ---
        if self.age_col in X.columns:
            mask_age = X[self.age_col] < self.min_age
            X.loc[mask_age, self.age_col] = self.min_age

        # --- Visit logic: only when ALL visit1 vars are missing ---
        v1_cols = [c for c in self.visit1_cols if c in X.columns]
        v2_cols = [c for c in self.visit2_cols if c in X.columns]

        if v1_cols and v2_cols:
            no_v1_mask = X[v1_cols].isna().all(axis=1)
            X.loc[no_v1_mask, v2_cols] = np.nan

        return X


sys.modules["main"] = sys.modules[__name__]




# ---------------------------------------------------------------
# Page config
# ---------------------------------------------------------------
st.set_page_config(page_title="Gbolahan Oladosu – Portfolio", layout="wide")


# ---------------------------------------------------------------
# Load model (if available)
# ---------------------------------------------------------------
@st.cache_resource
def load_model():
    model_path = "xgb_dropout_pipeline.pkl"

    # Check if the file exists first
    if not os.path.exists(model_path):
        st.error(f"Model file not found at: {model_path}")
        st.write("📂 Current working directory:", os.getcwd())
        st.write("📄 Files in this directory:", os.listdir("."))
        return None

    try:
        pipeline = joblib.load(model_path)
        st.success("✅ Model loaded successfully.")
        return pipeline
    except Exception as e:
        st.error(f"❌ Failed to load model: {e}")
        return None


pipeline = load_model()

# DEBUG: Show working directory and file contents
st.write("📂 Current working directory:", os.getcwd())
st.write("📄 Files in this directory:", os.listdir("."))
st.write("🗂 Assets folder:", os.listdir("assets") if os.path.exists("assets") else "assets NOT found")


# ---------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to:", ["Home", "Resume", "Projects", "Dropout Predictor"])


# ---------------------------------------------------------------
# HOME PAGE
# ---------------------------------------------------------------
if page == "Home":
    st.title("Welcome – Gbolahan Oladosu")
    
    if os.path.exists("assets/headshot.jpg"):
        st.image("assets/headshot.jpg", width=220)
    else:
        st.info("Headshot image coming soon.")

    st.subheader("Clinical Laboratory Scientist → Aspiring Clinical Data Scientist")

    st.markdown("""
    I am **Gbolahan Abdul-Rahman Oladosu**, currently working as a Clinical
    Laboratory Scientist and pursuing my M.S. in Data Science at Eastern University.

    My interests include:

    - Clinical trial analytics
    - Dropout prediction and patient retention
    - Healthcare & EHR machine learning
    - Model interpretability and fairness
    """)


# ---------------------------------------------------------------
# RESUME PAGE
# ---------------------------------------------------------------
elif page == "Resume":
    st.title("Resume")

    st.header("Education")
    st.write("""
    - M.S. Data Science – Eastern University
    - M.S. Biomedical Science – Roosevelt University
    """)

    st.header("Work Experience")
    st.write("""
    **Clinical Laboratory Scientist – Insight Hospital, Chicago**
    - High-complexity diagnostic testing
    - Quality control & lab operations
    - Applying data-driven thinking
    """)

    st.header("Skills")
    st.write("""
    - Python, R, SQL
    - scikit-learn, XGBoost, SHAP
    - Machine learning interpretability
    - Clinical and healthcare analytics
    """)
    if os.path.exists("assets/project_image.png"):
        st.image("assets/project_image.png", caption="Clinical Trial Analytics Dashboard")
    else:
        st.info("Project image coming soon.")


# ---------------------------------------------------------------
# PROJECTS PAGE
# ---------------------------------------------------------------
elif page == "Projects":
    st.title("Projects")

    st.subheader("Clinical Trial Dropout Prediction (Capstone Project)")
    st.write("""
    - Predicts whether a participant will drop out based on early-visit data
    - Models: Logistic Regression, Random Forest, XGBoost
    - Interpretability using SHAP
    """)

    st.info("""
    **Note:** All MSDS classwork remains private for academic integrity.
    """)


# ---------------------------------------------------------------
# DROPOUT PREDICTOR PAGE
# ---------------------------------------------------------------
elif page == "Dropout Predictor":
    st.title("Clinical Trial Dropout Predictor")

    if pipeline is None:
        st.error("Model not loaded. See messages above for details (missing file or load error).")
    else:
        st.markdown("Enter participant information below:")

        age = st.number_input("Age", min_value=18, max_value=100, value=65)
        sex = st.selectbox("Sex", ["Male", "Female"])
        race = st.selectbox("Race", ["White", "Black", "Asian", "Hispanic", "Other"])

        BMI = st.slider("BMI", 15.0, 45.0, 27.0)
        baseline_lab_score = st.slider("Baseline Lab Score", 0.0, 100.0, 50.0)
        disease_severity = st.slider("Disease Severity", 0.0, 10.0, 5.0)

        prior_treatments = st.number_input("Prior Treatments", 0, 20, 1)
        visit1_symptom_score = st.slider("Visit 1 Symptom Score", 0.0, 100.0, 50.0)
        visit1_adherence_rate = st.slider("Visit 1 Adherence", 0.0, 100.0, 80.0)
        visit1_AE_count = st.number_input("Visit 1 AE Count", 0, 20, 0)

        visit2_symptom_score = st.slider("Visit 2 Symptom Score", 0.0, 100.0, 45.0)
        visit2_adherence_rate = st.slider("Visit 2 Adherence", 0.0, 100.0, 75.0)
        visit2_AE_count = st.number_input("Visit 2 AE Count", 0, 20, 0)

        missed_appointments = st.number_input("Missed Appointments", 0, 20, 0)
        communication_score = st.slider("Communication Score", 0.0, 100.0, 60.0)

        if st.button("Predict Dropout Risk"):
            input_df = pd.DataFrame([{
                "age": age,
                "sex": sex,
                "race": race,
                "BMI": BMI,
                "baseline_lab_score": baseline_lab_score,
                "disease_severity": disease_severity,
                "prior_treatments": prior_treatments,
                "visit1_symptom_score": visit1_symptom_score,
                "visit1_adherence_rate": visit1_adherence_rate,
                "visit1_AE_count": visit1_AE_count,
                "visit2_symptom_score": visit2_symptom_score,
                "visit2_adherence_rate": visit2_adherence_rate,
                "visit2_AE_count": visit2_AE_count,
                "missed_appointments": missed_appointments,
                "communication_score": communication_score
            }])

            clinical_logic = pipeline.named_steps["clinical_logic"]
            missing_flags = pipeline.named_steps["missing_flags"]
            preprocess = pipeline.named_steps["preprocess"]
            model = pipeline.named_steps["model"]

            X_logic = clinical_logic.transform(input_df)
            X_flags = missing_flags.transform(X_logic)
            X_prep = preprocess.transform(X_flags)

            prob = model.predict_proba(X_prep)[0, 1]
            pred = model.predict(X_prep)[0]

            st.subheader("Prediction")
            st.write(f"**Dropout Probability:** `{prob:.3f}`")
            st.write(f"**Predicted Class:** {'Dropout' if pred == 1 else 'Completer'}")

            # SHAP
            explainer = shap.TreeExplainer(model)
            shap_values = explainer.shap_values(X_prep)

            st.subheader("Feature Importance (SHAP)")
            shap.initjs()
            fig, ax = plt.subplots(figsize=(8,4))
            shap.bar_plot(shap_values[0], max_display=10, show=False)
            st.pyplot(fig)