# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vduXPKUUBSKaSlaq9nlrAXkqBdn7FRx
"""
import os
import sys
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib.pyplot as plt

from sklearn.base import BaseEstimator, TransformerMixin  # needed for the custom transformer

# ============================
# 1. Custom Transformers
# ============================

class ClinicalConsistencyTransformer(BaseEstimator, TransformerMixin):
    """
    1. Age cleaning:
       - Any age < min_age is set to min_age (assume all participants are adults).

    2. Visit logic:
       - If ALL Visit 1 variables are missing, clear ALL Visit 2 variables to NaN.
       - This only triggers when visit1_symptom_score, visit1_adherence_rate, and visit1_AE_count
         are ALL NaN. If symptom is present (your 150-row case), nothing is touched.
    """
    def __init__(self,
                 visit1_cols=None,
                 visit2_cols=None,
                 age_col='age',
                 min_age=18):
        self.visit1_cols = visit1_cols or [
            'visit1_symptom_score',
            'visit1_adherence_rate',
            'visit1_AE_count'
        ]
        self.visit2_cols = visit2_cols or [
            'visit2_symptom_score',
            'visit2_adherence_rate',
            'visit2_AE_count'
        ]
        self.age_col = age_col
        self.min_age = min_age

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        X = X.copy()

        # --- Age cleaning ---
        if self.age_col in X.columns:
            mask_age = X[self.age_col] < self.min_age
            X.loc[mask_age, self.age_col] = self.min_age

        # --- Visit logic: only when ALL visit1 vars are missing ---
        v1_cols = [c for c in self.visit1_cols if c in X.columns]
        v2_cols = [c for c in self.visit2_cols if c in X.columns]

        if v1_cols and v2_cols:
            no_v1_mask = X[v1_cols].isna().all(axis=1)
            X.loc[no_v1_mask, v2_cols] = np.nan

        return X


class MissingIndicatorAdder(BaseEstimator, TransformerMixin):
    """
    Adds *_missing indicator columns (0/1) for selected columns.
    Example: visit1_adherence_rate -> visit1_adherence_rate_missing
    """
    def __init__(self, columns):
        self.columns = columns

    def fit(self, X, y=None):
        # nothing to learn
        return self

    def transform(self, X, y=None):
        X = X.copy()
        for col in self.columns:
            if col in X.columns:
                X[col + "_missing"] = X[col].isna().astype(int)
        return X






sys.modules["main"] = sys.modules[__name__]




# ---------------------------------------------------------------
# Page config
# ---------------------------------------------------------------
st.set_page_config(page_title="Gbolahan Oladosu – Portfolio", layout="wide")


# ---------------------------------------------------------------
# Load model (if available)
# ---------------------------------------------------------------
@st.cache_resource
def load_model():
    model_path = "xgb_dropout_pipeline.pkl"

    # Check if the file exists first
    if not os.path.exists(model_path):
        st.error(f"Model file not found at: {model_path}")
        st.write("📂 Current working directory:", os.getcwd())
        st.write("📄 Files in this directory:", os.listdir("."))
        return None

    try:
        pipeline = joblib.load(model_path)
        return pipeline
    except Exception as e:
        st.error(f"❌ Failed to load model: {e}")
        return None


pipeline = load_model()



# ---------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to:", ["Home", "Resume", "Projects", "Dropout Predictor"])


# ---------------------------------------------------------------
# HOME PAGE
# ---------------------------------------------------------------
# ---------------------------------------------------------------
# HOME PAGE
# ---------------------------------------------------------------
if page == "Home":
    st.title("👋 Welcome — I'm Gbolahan (Abdul) Oladosu")

    # Optional headshot
    col1, col2 = st.columns([1, 3])
    with col1:
        if os.path.exists("assets/headshot.jpg"):
            st.image("assets/headshot.jpg", width=200)
        else:
            st.info("Headshot coming soon!")

    with col2:
        st.markdown("""
        ### Clinical Laboratory Scientist → Aspiring Clinical Data Scientist  

        I specialize in applying machine learning to **clinical trial analytics**,  
        **healthcare data**, and **patient retention modeling**.

        My goal is to leverage my biomedical science background and data science  
        training to improve outcomes across healthcare and life sciences.
        """)

    st.markdown("---")

    # Highlight main project
    st.subheader("📌 Featured Project")
    st.markdown("""
    ### **Clinical Trial Dropout Prediction System**
    A machine learning platform that predicts early participant dropout using  
    demographic, clinical, and engagement variables.  
    Built with **XGBoost**, **scikit-learn**, **SHAP**, and deployed via **Streamlit**.

    👉 Navigate to **Projects** to learn more.  
    👉 Try the **Dropout Predictor** to see the model in action.
    """)

    st.markdown("---")

    # Quick navigation buttons
    st.subheader("📁 Quick Links")
    colA, colB, colC = st.columns(3)

    with colA:
        st.link_button("📄 View Resume", "#", help="Go to the Resume page")
    with colB:
        st.link_button("📊 Explore Projects", "#", help="Go to the Projects page")
    with colC:
        st.link_button("🧪 Dropout Predictor", "#", help="Try the ML model")

    st.markdown("---")

    st.caption(
        "This portfolio showcases my work in clinical analytics, machine learning, "
        "and applied data science."
    )

# ---------------------------------------------------------------
# RESUME PAGE
# ---------------------------------------------------------------
elif page == "Resume":
    st.title("Resume")

    # ----------------------------------------
    # Download Resume (PDF)
    # ----------------------------------------
    resume_path = "Resume.pdf"  # <--- YOUR FILE NAME

    if os.path.exists(resume_path):
        with open(resume_path, "rb") as f:
            st.download_button(
                label="📄 Download Resume (PDF)",
                data=f,
                file_name="Abdul_Oladosu_Resume.pdf",
                mime="application/pdf",
            )
    else:
        st.info("Resume PDF not found. Please upload Resume.pdf to the app directory.")



    # ----------------------------------------
    # Contact Section
    # ----------------------------------------
    st.subheader("Contact")
    st.write("**Location:** Chicago, IL")
    st.write("**Email:** goladosurahman@gmail.com")
    st.write("**Mobile:** 443-712-3471")
    st.write("**Portfolio:** https://clinical-dropout-app-m6i3x2gqrmc7hrf3kwy2za.streamlit.app/")
    st.write("**GitHub:** https://github.com/goladosu/Abdul-s_Portfolio")

    st.markdown("---")

    # ----------------------------------------
    # Education
    # ----------------------------------------
    st.subheader("Education")
    st.markdown("""
    - **M.S. Data Science**, Eastern University – St. Davids, PA *(Expected Dec 2025)*  
    - **M.S. Biomedical Science**, Roosevelt University – Chicago, IL *(2021–2022)*  
    - **B.Sc. Biomedical Science**, Gulf Medical University – Ajman, UAE *(2014–2018)*  
    """)

    st.markdown("---")

    # ----------------------------------------
    # Technical Skills
    # ----------------------------------------
    st.subheader("Technical Skills")
    st.markdown("""
    - **Languages:** Python, R, SQL  
    - **Libraries & Frameworks:** Pandas, NumPy, Scikit-learn, Matplotlib, ggplot  
    - **Tools & Platforms:** Power BI, Tableau, Excel, Google Colab, Jupyter Notebook, PyCharm  
    - **Core Competencies:** Machine Learning, Data Analysis, Predictive Modeling, SHAP, EDA  
    - **Soft Skills:** Communication, Leadership, Stakeholder Management, Rapport Building  
    """)

    st.markdown("---")

    # ----------------------------------------
    # Professional Experience
    # ----------------------------------------
    st.subheader("Professional Experience")
    st.markdown("""
    **Business Associate – Insight Hospital, Chicago, IL**  
    *Apr 2023 – Feb 2025*  
    - Conducted market research and competitive analysis, uncovering **10+ strategic insights** that informed hospital-level decision-making.  
    - Produced data-driven reports and presentations for leadership, enabling clear communication and actionable recommendations.  
    - Supported regulatory compliance, policy adherence, and operational alignment with industry standards.  
    """)

    st.markdown("---")

    # ----------------------------------------
    # Projects
    # ----------------------------------------
    st.subheader("Projects")

    st.markdown("""
    ### Clinical Trial Dropout Prediction System (Capstone Project)
    - Built an end-to-end ML system predicting early participant dropout using demographic, clinical, and behavioral trial data.  
    - Developed a domain-informed preprocessing pipeline including clinical logic checks, missingness indicators, imputation, scaling, and SMOTE.  
    - Evaluated Logistic Regression, Random Forest, and XGBoost; deployed **XGBoost (ROC-AUC: 0.969)**.  
    - Created a Streamlit web application with participant-level risk scores, SHAP explanations, and CRA-focused Low/Moderate/High risk guidance.

    ### Student Grade Prediction Model
    - Engineered ML models (Linear Regression, Lasso, SVR) to predict final student grades using early-term indicators.  
    - Achieved **RMSE ≈ 2.2** and **R² = 0.76** with Linear Regression.  
    - Identified key factors (attendance, study habits, prior failures) enabling early academic intervention strategies.
    """)


# ---------------------------------------------------------------
# PROJECTS PAGE
# ---------------------------------------------------------------
elif page == "Projects":
    st.title("Projects")

    # ----------------------------------------
    # Clinical Trial Dropout Prediction (Capstone)
    # ----------------------------------------
    st.subheader("Clinical Trial Dropout Prediction System (Capstone Project)")
    st.markdown("""
    - Developed an end-to-end machine learning pipeline to predict early participant dropout using demographic, clinical, and engagement data.  
    - Designed a domain-driven preprocessing workflow: clinical logic checks, missingness indicators, imputation, scaling, and SMOTE.  
    - Evaluated Logistic Regression, Random Forest, and XGBoost; deployed **XGBoost (ROC-AUC: 0.969)**.  
    - Built a Streamlit app with participant-level risk scoring, SHAP explanations, and CRA-focused decision support.
    """)
    
    st.markdown("---")

    # ----------------------------------------
    # Student Grade Prediction Model
    # ----------------------------------------
    st.subheader("Student Grade Prediction Model")
    st.markdown("""
    - Built regression models (Linear Regression, Lasso, SVR) to predict final student grades using early-term academic and behavioral predictors.  
    - Achieved **RMSE ≈ 2.2** and **R² = 0.76** with Linear Regression.  
    - Identified key drivers such as attendance, study time, and prior failures, enabling early academic intervention strategies.
    """)

    st.markdown("---")



# ---------------------------------------------------------------
# DROPOUT PREDICTOR PAGE
# ---------------------------------------------------------------
elif page == "Dropout Predictor":
    st.title("Clinical Trial Dropout Predictor")

    # ----------------------------------------
    # Model performance summary (test set)
    # ----------------------------------------
    st.markdown("### Model Performance (Held-out Test Set)")

    with st.expander("View model comparison", expanded=False):
        perf_df = pd.DataFrame([
            {
                "Model": "Logistic Regression",
                "Accuracy": 0.750,
                "ROC-AUC": 0.861,
                "Precision (Dropout)": 0.570,
                "Recall (Dropout)": 0.760,
                "F1 (Dropout)": 0.650,
            },
            {
                "Model": "Random Forest",
                "Accuracy": 0.930,
                "ROC-AUC": 0.965,
                "Precision (Dropout)": 0.899,
                "Recall (Dropout)": 0.870,
                "F1 (Dropout)": 0.884,
            },
            {
                "Model": "XGBoost (deployed)",
                "Accuracy": 0.927,
                "ROC-AUC": 0.969,
                "Precision (Dropout)": 0.889,
                "Recall (Dropout)": 0.870,
                "F1 (Dropout)": 0.879,
            },
        ])

        st.dataframe(
            perf_df.style.format({
                "Accuracy": "{:.3f}",
                "ROC-AUC": "{:.3f}",
                "Precision (Dropout)": "{:.3f}",
                "Recall (Dropout)": "{:.3f}",
                "F1 (Dropout)": "{:.3f}",
            }),
            use_container_width=True,
        )

        st.caption(
            "Metrics computed on a held-out test set of 300 participants. "
            "This app currently uses the XGBoost model for predictions."
        )

    # ----------------------------------------
    # Input form for a single participant
    # ----------------------------------------
    if pipeline is None:
        st.error("Model not loaded. See messages above for details (missing file or load error).")
    else:
        st.markdown("Enter participant information below:")

        age = st.number_input("Age", min_value=18, max_value=100, value=65)
        sex = st.selectbox("Sex", ["Male", "Female"])
        race = st.selectbox("Race", ["White", "Black", "Asian", "Hispanic", "Other"])

        BMI = st.slider("BMI", 15.0, 45.0, 27.0)
        baseline_lab_score = st.slider("Baseline Lab Score", 0.0, 100.0, 50.0)
        disease_severity = st.slider("Disease Severity", 0.0, 10.0, 5.0)

        prior_treatments = st.number_input("Prior Treatments", 0, 20, 1)
        visit1_symptom_score = st.slider("Visit 1 Symptom Score", 0.0, 100.0, 50.0)
        visit1_adherence_rate = st.slider("Visit 1 Adherence", 0.0, 100.0, 80.0)
        visit1_AE_count = st.number_input("Visit 1 AE Count", 0, 20, 0)

        visit2_symptom_score = st.slider("Visit 2 Symptom Score", 0.0, 100.0, 45.0)
        visit2_adherence_rate = st.slider("Visit 2 Adherence", 0.0, 100.0, 75.0)
        visit2_AE_count = st.number_input("Visit 2 AE Count", 0, 20, 0)

        missed_appointments = st.number_input("Missed Appointments", 0, 20, 0)
        communication_score = st.slider("Communication Score", 0.0, 100.0, 60.0)

        if st.button("Predict Dropout Risk"):
            # 1. Build a one-row DataFrame for this participant
            input_df = pd.DataFrame([{
                "age": age,
                "sex": sex,
                "race": race,
                "BMI": BMI,
                "baseline_lab_score": baseline_lab_score,
                "disease_severity": disease_severity,
                "prior_treatments": prior_treatments,
                "visit1_symptom_score": visit1_symptom_score,
                "visit1_adherence_rate": visit1_adherence_rate,
                "visit1_AE_count": visit1_AE_count,
                "visit2_symptom_score": visit2_symptom_score,
                "visit2_adherence_rate": visit2_adherence_rate,
                "visit2_AE_count": visit2_AE_count,
                "missed_appointments": missed_appointments,
                "communication_score": communication_score,
            }])

            # 2. Run through the same pipeline components used in training
            clinical_logic = pipeline.named_steps["clinical_logic"]
            missing_flags = pipeline.named_steps["missing_flags"]
            preprocess = pipeline.named_steps["preprocess"]
            model = pipeline.named_steps["model"]

            X_logic = clinical_logic.transform(input_df)
            X_flags = missing_flags.transform(X_logic)
            X_prep = preprocess.transform(X_flags)

            # 3. Predict
            prob = model.predict_proba(X_prep)[0, 1]
            pred = model.predict(X_prep)[0]

            # ----------------------------------------
            # Prediction summary
            # ----------------------------------------
            st.subheader("Prediction")
            st.write(f"**Dropout Probability:** `{prob:.3f}`")
            st.write(f"**Predicted Class:** {'Dropout' if pred == 1 else 'Completer'}")

            # ----------------------------------------
            # How to interpret this prediction (CRA view)
            # ----------------------------------------
            if prob < 0.30:
                risk_level = "Low"
                st.success(
                    "Risk level: **Low**\n\n"
                    "- The model does **not** see strong signs of early dropout.\n"
                    "- Continue standard follow-up per protocol.\n"
                )
            elif prob < 0.60:
                risk_level = "Moderate"
                st.warning(
                    "Risk level: **Moderate**\n\n"
                    "- The participant has **some** risk factors for early dropout.\n"
                    "- Consider additional check-ins, adherence counseling, or reminders.\n"
                )
            else:
                risk_level = "High"
                st.error(
                    "Risk level: **High**\n\n"
                    "- The model detects **several features** associated with early dropout.\n"
                    "- Flag this participant for proactive retention outreach "
                    "(e.g., phone call, coordinator/nurse consultation).\n"
                )

            st.caption(
                "This risk score is based on data available up to Visit 2. "
                "It is designed to support, not replace, clinical judgment and "
                "conversations with the participant."
            )

            # ----------------------------------------
            # SHAP feature importance for this prediction
            # ----------------------------------------
            st.subheader("Feature Importance (SHAP)")

            try:
                explainer = shap.TreeExplainer(model)
                shap_values = explainer.shap_values(X_prep)

                # For binary classification, shap_values may be a list [class0, class1]
                if isinstance(shap_values, list):
                    sv = shap_values[1][0]  # focus on dropout class
                else:
                    sv = shap_values[0]

                # Try to get meaningful feature names from the preprocess step
                try:
                    feature_names = preprocess.get_feature_names_out()
                except Exception:
                    feature_names = np.array([f"Feature {i}" for i in range(len(sv))])

                # Sort features by absolute SHAP value (top 10)
                idx = np.argsort(np.abs(sv))[::-1][:10]
                top_vals = sv[idx]
                top_features = feature_names[idx]

                fig, ax = plt.subplots()
                colors = ["#1f77b4" if v < 0 else "#d62728" for v in top_vals]
                ax.barh(top_features, top_vals, color=colors)
                ax.set_xlabel("SHAP value (impact on dropout prediction)")
                ax.set_title("Top Features Influencing This Prediction")
                ax.invert_yaxis()
                st.pyplot(fig)

            except Exception as e:
                st.warning(f"Could not render SHAP feature importance: {e}")
